language: ruby

rvm:
  - 2.4.1

env:
  global:
    - CAPNP_RELEASE_URL="https://github.com/OneSignal/capnproto-debian/releases/download/onesignal-0.6.1-1"
    - CAPNP_DEB="capnproto_0.6.1-1_amd64.deb"
    - CAPNP_LIB_DEB="libcapnp-0.6.1_0.6.1-1_amd64.deb"
    - CAPNP_LIB_DEV_DEB="libcapnp-dev_0.6.1-1_amd64.deb"
    - CXX=g++-7

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-7 g++-7 -y
  - curl -sSLO "${CAPNP_RELEASE_URL}/$(CAPNP_DEB)"
  - curl -sSLO "${CAPNP_RELEASE_URL}/${CAPNP_LIB_DEB}"
  - curl -sSLO "${CAPNP_RELEASE_URL}/${CAPNP_LIB_DEV_DEB}"
  - sudo dpkg -i ${CAPNP_DEB} ${CAPNP_LIB_DEB} ${CAPNP_LIB_DEV_DEB}

script:
  - gem install gem-compiler
  - gem build capn_proto.gemspec
  - gem compile $(ls capn_proto-*.gem) --prune

deploy:
  provider: releases
  api_key:
    secure: "gtnw2ob+VpJDL0aibq8V/IOH67Qrk8WuY9op6QCmgKlO55ehdLZIOvVVzAP1EYYYxpIJHBXc9zlb/9PPVF9r5wr0/KlttKbgYfsxPxRqQbZdIwRnPfB8/4ki1O3NJ+AsRztJ/78INjx1GX6YBgCgm+mh9QITpP7Gx5XpReMbeBtk/kR6jaofBcNJE6I+rY0loGcY4pDXrozRhnTJCEn1ykEjIs25A0rlJlzM9UK4fCR1MTofC9WjNbwJcJD9iSuea9+pPdRov1NBa7I1izBHCJSvb0NrtRAZgzj2slyUbUXlbr26tAFRQGs7WPLIaZl+B9mfv9p3hFfxO+7TYiyD1IfYW97nfZMcb6f0oaqTN0muW+FrFtQoD6B3H5LXdPWhemEPtQHvujSB7J5e4mmPfJ7RjMmFdIO5I8ZnOi61AgMo5xJ91c+u06yp/LpJxdkbT94pjVcCRe2MLRG5hz3XdwI4bfuMfgwqerNUZJDFHlCsVP2Lph4R2au6MxIb3WS+NsUjA0/sEahKtB3pdjRuwWsGH5UNwLoHVheLoMi2RGGPiOtJwlzhxlaw5B47AWUqk5Guj0vsm1t53tGrEgj4UaO2fc3Ej3u5u35V9iayy2FeIkwg0LppkiThvfFhin61VmfxxEdAc3jxVnpsWH6Zx/ljYVDWFE9Sr2JUYETVh3M="
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file: '*.gem'
  on:
    tags: true

