sudo: required
language: generic

services:
  - docker

env:
  global:
    - CAPNPROTO_RELEASE_URL="https://github.com/OneSignal/capnproto-debian/releases/download/onesignal-0.6.1-1"
    - CAPNPROTO_DEB="capnproto_0.6.1-1_amd64.deb"
    - LIBCAPNP_DEB="libcapnp-0.6.1_0.6.1-1_amd64.deb"
    - LIBCAPNP_DEV_DEB="libcapnp-dev_0.6.1-1_amd64.deb"

script:
  - ./build.sh

deploy:
  provider: releases
  api_key:
    secure: "uRvXaIhabipWT0TAvYug6bGzxWYpM7PAn6oYavYtrM7aLhyv/jqQffGFBZe21wo7bMRN95gi7WAQTQLDU11iBxvQjVtJ16FsL4hxSWJtsyh+4H4bJF2+qhS0WAW1aHzCRMuQIZOGHxqp1E2CPkiSdGpYNWdmnoSkCtzZBN7Ol9hNwt6NAhN5P5NeCQ+bjzF561lCLCvwuUD0/bcnZEbOsi6EitDjab01H7NgTpYY+3FjaCiqOYLI8bBrN8/Kx7JOrQuzoeK3x6rRoMulyowQmCeITyTEpw/PjVyDXXkJxSWekecGUbHmu7xRZruBE9CtU7ACZpn2r2S4uuFxhQ6QlDf4MeH6nk6hSLZ7T/FgEEZU7k4p1JNZEncLDQn869AukgFPfEKBhFz5SdsvTYUwewPoRXA+9+eDn75g+9GAk2QJeAp7Hx5hbr5nT0ikLoUPxllmBqPpqgGy3QeYrH2qoDFrda7b9VeaoFX3UZt7FImqpZbqZLBoFK8WgZIPjgW1/bGjmQOToWuHyk2jE2GKfVJFeaxiwTVdVKl3JqswzkSr+S/e6vn1DwGva2nZw0cVbN6BrZn7DKPc7gy4GmeKK12o4yc7rq/7bISPknzazko1vqZlr4xNhXgTyxyP4RPC9o8URkYu3Bq5iwAeYIhjGYNFztz7upEO3a5aTIrVRok="
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file: '*.gem'
  on:
    tags: true

